Blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('blogs.urls')),
]

accounts/urls.py
from django.urls import path,include
from . import views
app_name='accounts'
urlpatterns=[
  # 包含默认的身份验证url
  path('',include('django.contrib.auth.urls')),
  # 注册页面
  path('register/',views.register,name='register'),
]

blogs/urls.py
"""定义blogs的URL模式"""
from django.urls import path
from . import views
app_name='blogs'
urlpatterns=[
  # 主页
  path('',views.index,name='index'),
  path('topics/',views.topics,name='topics'),
  #特定主体的详细页面
  path('topics/<int:topic_id>/',views.topic,name='topic'),
  # 用于添加新主题的网页
  path('new_topic/',views.new_topic,name='new_topic'),
  # 给网址取别称，方便修改
  path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
  # 修改博客内容
  # 是不是用这个别称的时候就会调用view里面的new_entry函数？
  path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
  path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry')
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class BlogPost(models.Model):
  """用户A发的博客"""
  title=models.CharField(max_length=50)
  # 标题
  date_added=models.DateTimeField(auto_now_add=True)
  # 编辑日期
  text=models.TextField(default="")
  # Blog内容
  owner=models.ForeignKey(User,on_delete=models.CASCADE)
  def __str__(self):
    return self.title
class Entry(models.Model):
  """用户B对此的评论"""
  topic=models.ForeignKey(BlogPost,on_delete=models.CASCADE)
  text=models.TextField()
  date_added=models.DateTimeField(auto_now_add=True)
  owner=models.ForeignKey(User,on_delete=models.CASCADE)
  class Meta:
    verbose_name_plural='entries'
  def __str__(self):
    """返回一个表示条目的简单字符串"""
    res=self.text[:50]
    if(len(self.text)>50):res+="..."
    return res

blogs/forms.py
from django import forms
from .models import BlogPost,Entry
class TopicForm(forms.ModelForm):
  class Meta:
    model=BlogPost
    fields=['title','text']
    labels={'title':'Title',
            'text':'Text',
            }
    widgets = {
            'title': forms.Textarea(attrs={
                'rows': 1,
                'placeholder': '请输入标题…'
            }),
            'text': forms.Textarea(attrs={
                'rows': 8,
                'placeholder': '请输入正文内容（支持markdown）…'
            }),
        }
class EntryForm(forms.ModelForm):
  class Meta:
    model=Entry
    fields=['text']
    labels={'text':''}
    widgets={'text':forms.Textarea(attrs={'cols':80,
                                          'placeholder': '请输入评论内容（支持markdown）…',
                                          })}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
  """注册新用户"""
  if request.method!="POST":
    print("request.method!=post")
    # 显示空的注册表单
    form=UserCreationForm()
  else:
    # 处理填写好的表单
    form=UserCreationForm(data=request.POST)
    if form.is_valid():
      new_user=form.save()
      login(request,new_user)
      return redirect('blogs:index')
  context={'form':form}
  return render(request,'registration/register.html',context)

blogs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import BlogPost,Entry
from .forms import TopicForm,EntryForm
from django.http import Http404
# Create your views here.
# from django.shortcuts import render

def index(request):
  """学习笔记的主页"""
  return render(request,'blogs/index.html')
def topics(request):
  """显示所有主题"""
  # topics=BlogPost.objects.filter(owner=request.user).order_by('date_added')
  # 只显示自己创建的主题
  topics=BlogPost.objects.order_by('date_added')
  # 显示所有主题
  context={'topics':topics}
  return render(request,'blogs/topics.html',context)
def topic(request,topic_id):
  """显示单个主题及其所有的条目"""
  topic=BlogPost.objects.get(id=topic_id)
  # if topic.owner != request.user:
  #   raise Http404
  entries=topic.entry_set.order_by('-date_added')
  context={'topic':topic,'entries':entries}
  return render(request,'blogs/topic.html',context)
@login_required
def new_topic(request):
  # print("add new_topic")
  """添加新主题"""
  if request.method!='POST':
    # 未提交数据：创建一个新表单
    form=TopicForm()
  else:
    # POST提交的数据：对数据进行处理
    form=TopicForm(data=request.POST)
    if form.is_valid():
      new_topic=form.save(commit=False)
      new_topic.owner=request.user
      new_topic.save()
      # form.save()
      return redirect('blogs:topics')
  context={'form':form}
  return render(request,'blogs/new_topic.html',context)
@login_required
def new_entry(request,topic_id):
  print("ckp")
  """在特定主题中添加新条目"""
  topic=BlogPost.objects.get(id=topic_id)
  if request.method !='POST':
    form=EntryForm()
  else:
    form=EntryForm(data=request.POST)
    if form.is_valid():
      new_entry=form.save(commit=False)
      new_entry.owner=request.user
      new_entry.topic=topic
      new_entry.save()
      # 提交后进行重定向并传一个topic_id参数
      return redirect('blogs:topic',topic_id=topic_id)
  context={'topic':topic,'form':form}
  # 返回对应的html页面
  return render(request,'blogs/new_entry.html',context)
@login_required
def edit_entry(request,entry_id):
  """编辑既有的条目"""
  entry=Entry.objects.get(id=entry_id)
  topic=entry.topic
  if entry.owner!=request.user:
    # 不是评论发起人
    raise Http404
  if request.method!='POST':
    form=EntryForm(instance=entry)
  else:
    form=EntryForm(instance=entry,data=request.POST)
    if form.is_valid():
      form.save()
      return redirect('blogs:topic',topic_id=topic.id)
  context={'entry':entry,'topic':topic,'form':form}
  return render(request,'blogs/edit_entry.html',context)
@login_required
def edit_topic(request,topic_id):
  topic=BlogPost.objects.get(id=topic_id)
  if topic.owner!=request.user:
    raise Http404
  if request.method != 'POST':
        # 初次打开页面：表单预填充
        form = TopicForm(instance=topic)
  else:
        # 提交修改：把表单绑定到这个 topic 上
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:topic', topic_id=topic.id)
  context = {'topic': topic, 'form': form}
  return render(request, 'blogs/edit_topic.html', context)

blogs/templates/blogs/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>神秘の博客喵</title>
    <link rel="stylesheet" href="{% static 'css/codehilite.css' %}">

    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Live2DCubismCore -->
    <script src="https://cdn.jsdelivr.net/gh/litstronger/live2d-moc3@master/js/frame/live2dcubismcore.min.js"></script>
    <!-- Include Pixi. -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.6.1/pixi.min.js"></script>
    <!-- Include Cubism Components. -->
    <script src="https://cdn.jsdelivr.net/gh/litstronger/live2d-moc3@master/js/live2dcubismframework.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/litstronger/live2d-moc3@master/js/live2dcubismpixi.js"></script>
    <!-- User's Script -->
    <script src="https://cdn.jsdelivr.net/gh/litstronger/live2d-moc3@master/js/l2d.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/litstronger/live2d-moc3@master/js/main.js"></script>


    {%load django_bootstrap5%}
    {%bootstrap_css%}
    {%bootstrap_javascript%}
    <!-- 代码高亮样式 -->
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'blogs:index'%}">
        首页
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'blogs:topics'%}">
              博客
            </a>
          </li>
        </ul>
        <!-- 与账户相关的链接 -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {%if user.is_authenticated%}
            <li class="nav-item">
              <span class="navbar-text me-2">
                Hello,{{user.username}}
              </span>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:register'%}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:login'%}">
                Log in
              </a>
            </li>
            {%endif%}
          </ul>
          {%if user.is_authenticated%}
          <form action="{%url 'accounts:logout'%}" method="post">
            {%csrf_token%}
            <button name="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
          </form>
          {%endif%}
        </div>
      </div>
    </nav>
    <!-- 定义导航栏的代码到此结束 -->
    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {%block page_header%}{%endblock page_header%}
      </div>
      <div>
        {%block content%}{%endblock content%}
      </div>
    </main>
    
    <div class="Canvas"  id="L2dCanvas">
    <script>
        var config = {
            width: window.innerWidth*0.8,
            height: window.innerHeight*0.8,
            left: window.innerHeight+'px',
            bottom: '0px',
            basePath: 'https://cdn.jsdelivr.net/gh/alg-wiki/AzurLaneL2DViewer@gh-pages/assets',
            role: 'xuefeng_3',
            opacity: 1,
            mobile: false
        }
        var v = new Viewer(config); 
    </script>
    </div>
</body>
</html> 

blogs/templates/blogs/edit_entry.html
{%extends "blogs/base.html"%}
{%block content%}
  <p>
    <a href="{%url 'blogs:topic' topic.id%}">{{topic}}</a>
  </p>
  <p>Edit entry</p>
  <form action="{%url 'blogs:edit_entry' entry.id%}" method="post">
    {%csrf_token%}
    {{form.as_div}}
    <button>Save changes</button>
  </form>
{%endblock content%}

blogs/templates/blogs/edit_topic.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Edit Blog: {{ topic.title }}</p>

  <form action="{% url 'blogs:edit_topic' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}
{%block page_header%}
  <div class="p-3 mb-4 bg-light border rouded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">欢迎来到本博客喵</h1>
      <p class="lead">随便逛逛就可以了喵</p>
        <a class="btn btn-primary btn-lg mt-1" href="{%url 'accounts:register'%}">Register &raquo;</a>
    </div>
  </div>
{%endblock page_header%}

blogs/templates/blogs/new_entry.html
{%extends "blogs/base.html"%}
{%block content%}
  <p><a href="{%url 'blogs:topic' topic.id%}">{{topic}}</a></p>
  <p>添加一条评论喵</p>
  <form action="{% url 'blogs:new_entry' topic.id%}" method="post">
    {%csrf_token%}
    {{form.as_div}}
    <button name="submit">Add entry</button>
  </form>
{%endblock content%}

blogs/templates/blogs/new_topic.html
{%extends "blogs/base.html"%}
{%block content%}
  <p>Add a new Blog:</p>
  <form action="{% url 'blogs:new_topic'%}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Add topic</button>
  </form>
{%endblock content%}
<!-- fuck ccf -->

blogs/templates/blogs/topic.html
{%extends 'blogs/base.html'%}
{%load markdownify%}
{%block page_header%}
  <h1>{{topic.title}}</h1>
  by {{topic.owner}}
  <p>{{topic.text|markdownify}}</p>
  <p>
    <a href="{% url 'blogs:edit_topic' topic.id %}">编辑内容喵</a>
  </p>
  {%endblock page_header%}
{%block content%}
  <p>
    <a href="{%url 'blogs:new_entry' topic.id%}">评论一句喵</a>
  </p>
  {%for entry in entries%}
    <div class="card mb-3">
      {% comment %} 包含时间戳和编辑链接的标题 {% endcomment %}
      <h4 class="card-header">
        {{entry.owner}} in {{entry.date_added|date:"M d, Y H:i"}}
        <small>
          <a href="{%url 'blogs:edit_entry' entry.id%}">
            编辑评论喵
          </a>
        </small>
      </h4>
      {% comment %} 包含条目文本的正文 {% endcomment %}
      <div class="card-body">
        {% comment %} {{entry.text|linebreaks}} {% endcomment %}
        {{entry.text|markdownify}}
      </div>
    </div>
  {%empty%}
  <p>这里没有任何人评论过喵</p>
  {%endfor%}
{%endblock content%}

blogs/templates/blogs/topics.html
{%extends 'blogs/base.html'%}
{%load markdownify%}
{%block page_header%}
  <h1>博客</h1>
  <a href="{%url 'blogs:new_topic'%}">发布自己的博客喵</a>
{%endblock page_header%}
{%block content%}
  <ul class="list-group border-bottom pb-2 mb-4">
    {%for topic in topics%}
    <li class="list-group-item border-0">
      <p>
        <a href="{%url 'blogs:topic' topic.id %}">
        {{topic.title}}
        </a>
        by {{topic.owner}}
      </p>
      <p>{{topic.date_added|date:"M d, Y H:i"}}</p>
    </li>
    {%empty%}
    <li class="list-group-item border-0">没有博客喵</li>
    {%endfor%}
  </ul>
{%endblock content%} 